### ISSUE TITLE
IPv6 load-balancer error AtleastOneIpV4RequiredForIpV6LbFrontendIpConfiguration

### ISSUE THREAD

**Issue by rastislavs** [kubernetes-sigs/cloud-provider-azure#1831]
#### What happened:
In a dual-stack cluster, when creating an IPv6 LoadBalancer service, the Azure CCM returns the following error and the service stays in the pending state:

```
"error": {
    "code": "AtleastOneIpV4RequiredForIpV6LbFrontendIpConfiguration",
    "message": "At least one IPv4 frontend ipConfiguration is required for an IPv6 frontend ipConfiguration on the load balancer '/subscriptions/528474a9-8cc6-46c8-9b74-1dbc31c4bb7f/resourceGroups/kubernetes-xszcklqrmv/providers/Microsoft.Network/loadBalancers/kubernetes'",
    "details": []
  }
```

```

nginx-ipv6-lb   LoadBalancer   fd02::42      <pending>     80:30278/TCP   7m15s
```

#### What you expected to happen:

As per https://github.com/kubernetes-sigs/cloud-provider-azure/issues/814, dual-stack is not fully supported, but the Azure CCM should be able to create a single-stack IPv6 LB.

#### How to reproduce it (as minimally and precisely as possible):
- create a dual-stack cluster (IPv4 as the primary IP family, IPv6 as the secondary).
- create an IPv6-only service, such as:

```
apiVersion: v1
kind: Service
metadata:
  name: nginx-ipv6-lb
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv6
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
```

#### Environment:

- Kubernetes version (use `kubectl version`): 1.24.0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Ubuntu "20.04.4 LTS
- Kernel (e.g. `uname -a`): 5.13.0-1029-azure
- Install tools:
- Network plugin and version (if this is a network-related bug): Canal v3.22.1
- Others:
