### ISSUE TITLE
AKS Private Link Service requires global visbility

### ISSUE THREAD

**Issue by Minh-Ng** [kubernetes-sigs/cloud-provider-azure#1859]
#### What happened:
Creating a private link service as [follows](https://github.com/kubernetes-sigs/cloud-provider-azure/issues/872):
```
apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: my-namespace
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-pls-create: "true"
    # Does not work without: service.beta.kubernetes.io/azure-pls-visibility: "*"
    # service.beta.kubernetes.io/azure-pls-visibility: "<UUID>" does not work either
    service.beta.kubernetes.io/azure-pls-auto-approval: "<UUID>"
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: my-app
```

The auto approval does not apply without pls-visibility set to *. The following controller event is surfaced: `reconcilePLSVisibility: autoApproval only takes effect when visibility is set to "*"`

#### What you expected to happen:
I should be able to specify visibility and approval to the same subscription, removing the need for global visibility. This capability is present in the console: 
<img width="787" alt="Screen Shot 2022-06-16 at 1 30 30 PM" src="https://user-images.githubusercontent.com/4149877/174158388-d60f1087-2a6b-4683-918f-668ebd8e97b1.png">

```
service.beta.kubernetes.io/azure-pls-visibility: *
service.beta.kubernetes.io/azure-pls-auto-approval: "<UUID>"
``` 
is the third option and not ideal.

#### How to reproduce it (as minimally and precisely as possible):
Apply service definition above.

#### Anything else we need to know?:
N/A

#### Environment:
AKS

- Kubernetes version (use `kubectl version`): AKS 1.22.4
- Cloud provider or hardware configuration: AKS
- OS (e.g: `cat /etc/os-release`): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Network plugin and version (if this is a network-related bug): N/A
- Others:
