### ISSUE TITLE
Windows nodes are not assigned IPv6 InternalIP in a dual-stack cluster

### ISSUE THREAD

**Issue by tyler-lloyd** [kubernetes-sigs/cloud-provider-azure#3213]
In dual-stack clusters with Windows nodes, the Windows nodes are not assigned an IPv6 InternalIP even when the VM has an IPv6 IP configuration. The Linux nodes in the same cluster get their IPv6 addresses successfully.

Here are the 2 VMSS instances in the dual-stack cluster (1 Linux, 1 Windows).

![Screenshot from 2023-01-20 09-06-00](https://user-images.githubusercontent.com/19452592/213716126-1398eb5e-2ad4-40fc-b5eb-d08ed2601c42.png)

The Linux node has both InternalIPs:

```
  status:
    addresses:
    - address: aks-nodes-24368634-vmss000000
      type: Hostname
    - address: 10.224.0.4
      type: InternalIP
    - address: fde0:1e2d:ece5:4d42::5
      type: InternalIP
```

But the Windows node only has IPv4

```
  status:
    addresses:
    - address: 10.224.0.5
      type: InternalIP
    - address: aksnpwin000000
      type: Hostname

```

#### What happened:

Windows nodes do not get the IPv6 address on the VM assigned as an InternalIP

#### What you expected to happen:

Both IPv4 and IPv6 addresses from the VNet are assigned as InternalIPs on the node; parity with Linux nodes.

#### How to reproduce it (as minimally and precisely as possible):

Create a cluster with Windows nodes and use `--network-plugin azure --network-plugin-mode overlay --ip-families ipv4,ipv6`. This is on a development branch with dual-stack CNI Overlay so it can only be created internally to Microsoft.

#### Environment:

- Kubernetes version (use `kubectl version`): 1.24.6
- Cloud provider or hardware configuration: Azure (AKS)
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.6 and Windows Server 2022 Datacenter
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug): Azure CNI Overlay with dual-stack
- Others:
