### ISSUE TITLE
Add support for server-side encryption 

### ISSUE THREAD

**Issue by lhaussknecht** [kubernetes-sigs/cloud-provider-azure#334]
**Is your feature request related to a problem? Please describe.**
We need to use our own Azure KeyVault and encrypt disks with it. Therefore all our disks are part of an disk-encryption-set.
Unfortunately when using the dynamic disk provisioner, the disks are not encrypted. Detaching an disk to then add it to the disk-encryption-set is not an easy task and involves downtimes.

**Describe the solution you'd like in detail**
I want to provide the name of the disk-encryption set, which is then used when the provisioner creates a new disk. The disk is then encrypted and ready to use.

**Describe alternatives you've considered**
We are using pre-provides PersistentVolumes which we created before using 
`az disk create -n encrypted_disk_name--size-gb 128 --disk-encryption-set diskencryptionset --encryption-type EncryptionAtRestWithCustomerKey`

**Additional context**
https://docs.microsoft.com/en-us/azure/virtual-machines/windows/disk-encryption

**Comment by m-soltani** [comment]
We have the same issue in our organization and we want to be able to have dynamic disk provisioner use the disk-encryption-set feature.

**Comment by feiskyer** [comment]
does the following storageclass example work for you (note this is only supported since v1.17)? 

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: hdd
provisioner: kubernetes.io/azure-disk
parameters:
  skuname: Standard_LRS
  kind: managed
  diskEncryptionSetID: "/subscriptions/{subs-id}/resourceGroups/{rg-name}/providers/Microsoft.Compute/diskEncryptionSets/{diskEncryptionSet-name}"
```
