### ISSUE TITLE
Cannot deploy Azure CCM via Secret

### ISSUE THREAD

**Issue by TaylorFinklea** [kubernetes-sigs/cloud-provider-azure#3579]
#### What happened:
I'm trying to deploy via the helm chart and my cloud controller manager is stuck in a crash loop with this error:
`1 controllermanager.go:320] Run: Cloud provider azure could not be initialized dynamically from secret kube-system/cloud-provider-azure: NewCloudFromSecret: failed to initialize cloud from secret kube-system/cloud-provider-azure: InitializeCloudFromSecret: failed to get cloud config from secret kube-system/cloud-provider-azure: cloud-config is not set in the secret (kube-system/cloud-provider-azure)`
#### What you expected to happen:
Controller manager deploys as expected
#### How to reproduce it (as minimally and precisely as possible):
secret.yaml
```
apiVersion: v1
stringData:
	{
	  "cloud": "<VALUE>",
	  "tenantId": "<VALUE>",
	  "aadClientId": "<VALUE>",
	  "aadClientSecret": "<VALUE>",
	  "subscriptionId": "<VALUE>",
	  "resourceGroup": "<VALUE>",
	  "location": "centralus",
	  "subnetName": "talos-subnet",
	  "vnetName": "<VALUE>",
	  "vnetResourceGroup": "<VALUE>",
	  "cloudProviderBackoff": false,
	  "useManagedIdentityExtension": false,
	  "useInstanceMetadata": true
	}
kind: Secret
metadata:
  name: cloud-provider-azure
  namespace: kube-system
```
values
```
  values:
    cloudControllerManager:
      imageRepository: mcr.microsoft.com/oss/kubernetes
      imageName: azure-cloud-controller-manager
      cloudConfigSecretName: cloud-provider-azure
      cloudConfigSecretNamespace: kube-system
      enableDynamicReloading: true
      cloudConfig: ''
    cloudNodeManager:
      imageRepository: mcr.microsoft.com/oss/kubernetes
      imageName: azure-cloud-node-manager
      cloudConfig: ''
```
#### Anything else we need to know?:
I've tried deploying through flux, but also just deploying through helm and kubectl
#### Environment:

- Kubernetes version (use `kubectl version`): 1.26.2
- Cloud provider or hardware configuration: Omni deployed on Azure VMs
- OS (e.g: `cat /etc/os-release`): Talos 1.3.5
- Kernel (e.g. `uname -a`): 5.15.94-talos
- Install tools: Flux, kubectl, helm

**Comment by ljtill** [comment]
I recently faced the same problem and found this solution worked for me.

The `secret.yaml` manifest needs to be formatted in the following way:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: cloud-config
  namespace: kube-system
type: Opaque
stringData:
  cloud-config: |-
    {
        "cloud": "",
        "tenantId": "",
        "subscriptionId": "",
        // Config Values
        "vmType": "",
        "useInstanceMetadata": true,
        "useManagedIdentityExtension": true,
        "userAssignedIdentityID": "",
        "enableMultipleStandardLoadBalancers": true
      }
```

In order to address the problem of the controller persistently attempting to resolve the file path, the following arguments need to be set. Specifically, the cloudConfig property which needs to be assigned an empty string ("").

--set cloudControllerManager.cloudConfigSecretName=cloud-config
--set cloudControllerManager.enableDynamicReloading=true
--set cloudControllerManager.cloudConfig=""
