### ISSUE TITLE
How to specify resource group for PLS?

### ISSUE THREAD

**Issue by CiucurDaniel** [kubernetes-sigs/cloud-provider-azure#4608]
#### What happened:

I'm trying to deploy a load balancer which also creates  a Private Link Service but I want to specify a resource group and not use the default one.  However I do not fully understand the [docs section](https://cloud-provider-azure.sigs.k8s.io/topics/pls-integration/#creating-managed-privatelinkservice) about resource groups.

```
When a service is created with annotation service.beta.kubernetes.io/azure-pls-create set to true or updated later with the annotation added, a PLS resource attached to the LB frontend is created in the default resource group or the resource group user set in config file with key `PrivateLinkServiceResourceGroup`.
```

Suppose I have this LB definition, how would you define the private link resource group if I do not want the default rg used?
Are you supposed to add it as an annotation?

```yaml
apiVersion: v1
kind: Service
metadata:
  name: myService
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true" # Use an internal LB with PLS
    service.beta.kubernetes.io/azure-pls-create: "true"
    service.beta.kubernetes.io/azure-pls-name: myServicePLS
    service.beta.kubernetes.io/azure-pls-ip-configuration-subnet: pls-subnet
    service.beta.kubernetes.io/azure-pls-ip-configuration-ip-address-count: "1"
    service.beta.kubernetes.io/azure-pls-ip-configuration-ip-address: 10.240.0.9 # Must be available in pls-subnet
    service.beta.kubernetes.io/azure-pls-fqdns: "fqdn1 fqdn2"
    service.beta.kubernetes.io/azure-pls-proxy-protocol: "false"
    service.beta.kubernetes.io/azure-pls-visibility: "*"
    service.beta.kubernetes.io/azure-pls-auto-approval: "subId1"
spec:
  type: LoadBalancer
  selector:
    app: myApp
  ports:
    - name: myAppPort
      protocol: TCP
      port: 80
      targetPort: 80

```

#### What you expected to happen:

Docs would include an example on how to specify the resource group. 
https://cloud-provider-azure.sigs.k8s.io/topics/pls-integration/

As a side note, also "default resource group" is not clear enough. Should be made clear the default means the resource group of the aks nodes.

#### Environment:

Not relevant.
