### ISSUE TITLE
Private link service not created

### ISSUE THREAD

**Issue by parkerjgit** [kubernetes-sigs/cloud-provider-azure#4838]
#### What happened:

Attempted to create azure private link service using [PrivateLinkService annotations](https://cloud-provider-azure.sigs.k8s.io/topics/pls-integration/#privatelinkservice-annotations) for Nginx Ingress Controller following example [here](https://cloud-provider-azure.sigs.k8s.io/topics/pls-integration/#managed-privatelinkservice-creation-example) as well as nginx helm example [here](https://blog.baeke.info/2022/06/13/publish-your-aks-ingress-controller-over-azure-private-link/)

My nginx helm chart:

```
controller:
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      service.beta.kubernetes.io/azure-pls-create: "true"
      service.beta.kubernetes.io/azure-pls-name: "my-pls"
      service.beta.kubernetes.io/azure-pls-ip-configuration-subnet: "pls-snet"
      service.beta.kubernetes.io/azure-pls-ip-configuration-ip-address-count: "1"
      service.beta.kubernetes.io/azure-pls-ip-configuration-ip-address: "10.210.2.10" # any avail id in subnet
      service.beta.kubernetes.io/azure-pls-proxy-protocol: "false"
      service.beta.kubernetes.io/azure-pls-visibility: '*'
```

LoadBalancer is generated with yaml:

```
kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
  annotations:
    meta.helm.sh/release-name: ingress-nginx
    meta.helm.sh/release-namespace: ingress-nginx
    service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
    service.beta.kubernetes.io/azure-pls-create: 'true'
    service.beta.kubernetes.io/azure-pls-ip-configuration-ip-address: 10.210.2.10
    service.beta.kubernetes.io/azure-pls-ip-configuration-ip-address-count: '1'
    service.beta.kubernetes.io/azure-pls-ip-configuration-subnet: pls-snet
    service.beta.kubernetes.io/azure-pls-name: my-pls
    service.beta.kubernetes.io/azure-pls-proxy-protocol: 'false'
    service.beta.kubernetes.io/azure-pls-visibility: '*'
...
spec:
  ports:
    - name: http
      protocol: TCP
      appProtocol: http
      port: 80
      targetPort: http
      nodePort: 30683
    - name: https
      protocol: TCP
      appProtocol: https
      port: 443
      targetPort: https
      nodePort: 31405
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  clusterIP: 10.0.46.253
  clusterIPs:
    - 10.0.46.253
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  allocateLoadBalancerNodePorts: true
  internalTrafficPolicy: Cluster
status:
  loadBalancer:
    ingress:
      - ip: 10.210.0.95
```

#### What you expected to happen:

PLS resource attached to the LB frontend is created in the default resource group with key PrivateLinkServiceResourceGroup as described [here](https://cloud-provider-azure.sigs.k8s.io/topics/pls-integration/#creating-managed-privatelinkservice). "Default" is assumed to be the aks managed resource group.

#### How to reproduce it (as minimally and precisely as possible):

1. create vnet
2. create aks instance with:
    * Azure CNI
    * standard load balancer sku
    * system-assigned identity
3. create ingress:
    ```
    helm upgrade \
                --install ingress-nginx ingress-nginx \
                --repo https://kubernetes.github.io/ingress-nginx \
                --namespace ingress-nginx \
                --create-namespace \
                -f ./ingress/values.yaml
    ```

#### Anything else we need to know?:

* aks is deployed with terraform
* first time so assum I'm doing smth dumb, but I don't understand how to troubleshoot this.
* vnet: 10.210.0.0/16
    * subnet for aks: 10.210.0.0/24
    * subnet for pls (ie "pls-snet"): 10.210.2.0/24

#### Environment:

- Kubernetes version (use `kubectl version`): unk.
- Cloud provider or hardware configuration: AKS
- OS (e.g: `cat /etc/os-release`): Ubuntu
- Kernel (e.g. `uname -a`): n/a
- Install tools: n/a
- Network plugin and version (if this is a network-related bug): n/a
- Others:
