### ISSUE TITLE
NSG rule not created when setting IPv6 single stack allowed source range in v1.26 and v1.25

### ISSUE THREAD

**Issue by lodrem** [kubernetes-sigs/cloud-provider-azure#5366]
#### What happened:

``` yaml
apiVersion: v1
kind: Service
metadata:
  name: foo
spec:
  type: LoadBalancer
  selector:
    app: foo
  ipFamilies:
  - IPv6
  ipFamilyPolicy: SingleStack
  loadBalancerSourceRanges:
  - fd00::/8
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
```

When applying the above manifest, the NSG rule was not created as expected.

#### What you expected to happen:

An NSG rule for IPv6 was created.

#### Anything else we need to know?:

It's a bug exposed in #5123 that doesn’t properly handle the scenario of a single IPv6 stack.

#### Environment:

- Kubernetes version (use `kubectl version`): v1.26 / v1.25
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
