### ISSUE TITLE
Invalid LoadBalancerSourceRanges when there are spaces in the range values

### ISSUE THREAD

**Issue by feiskyer** [kubernetes-sigs/cloud-provider-azure#5883]
#### What happened:

Invalid LoadBalancerSourceRanges when there are spaces in the range values. e.g. for the following service spec:

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
    service.beta.kubernetes.io/load-balancer-source-ranges: 172.0.0.0/8, 10.0.0.0/8
```

The following error would be generated (warning event):

```
0s          Warning   InvalidConfiguration   service/echoserver   Found invalid LoadBalancerSourceRanges [ 10.0.0.0/8], ignoring and adding a default DenyAll rule in security group.
```

#### What you expected to happen:

Cloud provider should strip the spaces and configure NSG successfully.

#### Environment:

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
