### ISSUE TITLE
Editing identically named services in different namespaces from `type: ClusterIP` to `type: LoadBalancer` creates two IPs which point to the same namespace

### ISSUE THREAD

**Issue by migleeson** [kubernetes-sigs/cloud-provider-azure#653]
**What happened**:

Creating two namespaces (A and B) with identically named `ClusterIP` services, and then using `kubectl edit -n <namespace> svc <svc_name>` to change the type of each service to `LoadBalancer` results in two separate public IP addresses (as expected) which both route to the same service in namespace A (not expected)

**What you expected to happen**:

Expected behaviour is to provide an endpoint to each service in namespaces A and B, and not have two IPs for the service in namespace A

**How to reproduce it**:

I use a lot of code to spin up this environment, but the gist is:

1. Create namespaces A and B. In my case they're named `work-environment-100` and `work-environment-101`.

2. Create an identically named deployment in namespaces A and B (in the `metadata.name` portion of the deployment spec) with identical tags and labels. Example:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: {namespace}
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:5.0.1
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1.5Gi"
              cpu: "1000m"
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-service:9092"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
          ports:
            - containerPort: 9092
```

3. Create identically named services in each namespace A and B with identical selectors with default type:
```
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: {namespace}
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
```

4. Finally, edit the services to be `LoadBalancer`s to get a public IP:
```
k -n work-environment-100 edit svc/kafka-service
```
Swap 
```
type: ClusterIP
```
for
```
type: LoadBalancer
```

5. Traffic to those IPs will route to the same namespace incorrectly.
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"ac26f1b96417683d8d13ed3c38bffdfe2ebd5520", GitTreeState:"clean", BuildDate:"2021-03-10T23:38:06Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):
```
Linux mikepc-MS-7B86 5.4.0-74-generic #83~18.04.1-Ubuntu SMP Tue May 11 16:01:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Others:
