### ISSUE TITLE
Migrate test-infra jobs to community clusters

### ISSUE THREAD

**Issue by nilo19** [kubernetes-sigs/cloud-provider-azure#6577]
#### What would you like to be added:

Migrate test-infra jobs to community clusters

**Comment by nilo19** [comment]
waiting for https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/4976

**Comment by dtzar** [comment]
@nilo19 do not wait for all of our tests to finish here.  You should be able to get started now to make the deadline.

I created a [separate report here ](https://github.com/dtzar/test-infra/blob/nawaz-azure/hack/cluster-migration/cloud-provider-azure-job-migration-todo.md) for all the tests which need to be migrated that I can update periodically for status.

**Comment by dtzar** [comment]
https://github.com/kubernetes/test-infra/pull/33048 is related to this issue

**Comment by nojnhuh** [comment]
This issue will likely also require updating any templates here used with CAPZ 1.16 to use an AzureClusterIdentity with WorkloadIdentity: https://github.com/kubernetes-sigs/cloud-provider-azure/tree/master/tests/k8s-azure/manifest/cluster-api. The one we use in our test for ci-entrypoint looks like this:
```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterIdentity
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move-hierarchy: "true"
  name: ${CLUSTER_IDENTITY_NAME}
  namespace: default
spec:
  allowedNamespaces: {}
  clientID: ${AZURE_CLIENT_ID_USER_ASSIGNED_IDENTITY}
  tenantID: ${AZURE_TENANT_ID}
  type: WorkloadIdentity
```
