### ISSUE TITLE
OverlappingSubnetsNotPermittedInSecurityRule occurs when using overlapping CIDR as allowed source ranges

### ISSUE THREAD

**Issue by zarvd** [kubernetes-sigs/cloud-provider-azure#6775]
#### What happened:

OverlappingSubnetsNotPermittedInSecurityRule occurs when using overlapping CIDR blocks as allowed source ranges.

#### What you expected to happen:

no error

#### How to reproduce it (as minimally and precisely as possible):

set overlap CIDR in `spec.LoadBalancerSourceRanges` or `annotation: service.beta.kubernetes.io/azure-allowed-ip-ranges`

``` yaml
apiVersion: v1
kind: Service
metadata:
  name: conflict
  annotations:
    service.beta.kubernetes.io/azure-allowed-ip-ranges: "10.0.0.0/8,10.0.0.0/16" // overlap
spec:
  type: LoadBalancer
  selector:
    app: conflict
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: tcp
    port: 4000
    protocol: TCP
    targetPort: 4000
```

#### Anything else we need to know?:

It’s because of the change made in #5164, and it’s only going to impact clusters with version >= 1.29.

#### Environment:

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
