### ISSUE TITLE
[Feat][Credential Provider] Registry mirror mapping

### ISSUE THREAD

**Issue by lzhecheng** [kubernetes-sigs/cloud-provider-azure#6845]
#### What would you like to be added:

Need a new feature to support registry mirror mapping for credential provider. For example, the image URL is `mcr.microsoft.com/test/acronly:dev`, and credential provider fetches credential from `xxx.azurecr.io` ACR.

Steps:

1. docker push an image to an ACR `xxx.azurecr.io/test/acronly:dev` and set annonymous pull to false
2. Set up [containerd config](https://github.com/containerd/containerd/blob/main/docs/hosts.md#simple-default-host-config-for-docker) on Node 
```/etc/containerd/certs.d/mcr.microsoft.com# cat hosts.toml
server = "https://mcr.microsoft.com"

[host."https://xxx.azurecr.io"]
  capabilities = ["pull", "resolve"]
```
3. Set up `/var/lib/kubelet/credential-provider-config.yaml`
```
apiVersion: kubelet.config.k8s.io/v1
kind: CredentialProviderConfig
providers:
  - name: acr-credential-provider
    matchImages:
      - "*.azurecr.io"
      - "*.azurecr.cn"
      - "*.azurecr.de"
      - "*.azurecr.us"
      - "mcr.microsoft.com"
    defaultCacheDuration: "10m"
    apiVersion: credentialprovider.kubelet.k8s.io/v1
    args:
      - /etc/kubernetes/azure.json
      - --mirror-mapping=mcr.microsoft.com:xxx.azurecr.io
```
5. Create a Pod using image `mcr.microsoft.com/test/acronly:dev` and image pull is successful

#### Why is this needed:

Credential provider supports registry host namespace in containerd config
