### ISSUE TITLE
Error creating LoadBalancer service on AKS due to invalid NSG rule configuration

### ISSUE THREAD

**Issue by CorentinRegnier** [kubernetes-sigs/cloud-provider-azure#8931]
#### What happened:

While creating a LoadBalancer service on AKS (Azure Kubernetes Service), an error occurred related to the creation of a Network Security Group (NSG) rule. The error message states:

```
Error syncing load balancer: failed to ensure load balancer: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: {"error":{"code":"SecurityRuleParametersUnsupportedForPortRanges","message":"Security rule with Id /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/my-rg/providers/Microsoft.Network/networkSecurityGroups/aks-agentpool-xxxxxx-nsg/securityRules/k8s-azure-lb_allow_IPv4_xxxxxxx must specify a non-empty value for either DestinationPortRange or DestinationPortRanges, but not both.","details":[]}}
```

(can see it on azure portal activity log and can see diff apply too)

This error is preventing the creation of the LoadBalancer as the format of the security rule is incorrect.

#### What you expected to happen:

The LoadBalancer service should be created successfully, and the corresponding NSG rule should be applied without errors.

#### How to reproduce it (as minimally and precisely as possible):

1. Create a service of type `LoadBalancer` in AKS.
2. Observe the error in the service creation logs or events related to NSG configuration.

#### Anything else we need to know?:

- The AKS cluster uses the Azure Cloud Provider integration, with the `cloud-node-manager` pods running in the `kube-system` namespace.
- The error occurs when the `service-controller` tries to manage the NSG rules during the LoadBalancer creation.
- The issue might be related to how the security rule is being applied by the cloud provider.
- The error occurs because the Network Security Group (NSG) rule expects that either DestinationPortRange or DestinationPortRanges is set, but not both. When a single port is declared in the LoadBalancer service configuration, the same port is referenced in both DestinationPortRange and DestinationPortRanges. This leads to an invalid configuration, as both fields should not be populated with the same value. This causes the error SecurityRuleParametersUnsupportedForPortRanges.

This mismatch in the expected values for the NSG rule is what leads to the error SecurityRuleParametersUnsupportedForPortRanges.
#### Environment:

- Kubernetes version: `v1.31.5` (check with `kubectl version`)
- Cloud provider or hardware configuration: Microsoft Azure AKS
- OS: Ubuntu 22.04 (for worker nodes)
- Kernel: -
- Install tools: `kubectl`, `helm`
- Network plugin and version: Calico and kubelet
- Others: The AKS cluster uses the default `cloud-provider-azure` configuration with the `cloud-node-manager` pods managing Azure resources.

#### Service Configuration:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql80bddread
  namespace: mysql80
  labels:
    app.kubernetes.io/instance: percona-cluster
    app.kubernetes.io/name: percona-xtradb-cluster
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: percona-cluster
    app.kubernetes.io/name: percona-xtradb-cluster
    statefulset.kubernetes.io/pod-name: percona-cluster-pxc-1
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
  loadBalancerIP: "myip" 
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
```

#### Workaround:

Currently, as a workaround, I have found that if I set multiple ports for the service, the issue no longer occurs. For example, by adding an additional port configuration like this:

```yaml
ports:
  - name: mysql
    port: 3306
    targetPort: 3306
    protocol: TCP
  - name: mysql-alt
    port: 3307
    targetPort: 3307
    protocol: TCP
```

This allows the LoadBalancer to be created successfully without the error, and it resolves the issue related to the NSG rule creation. This is my current solution until a more permanent fix is implemented.
