### ISSUE TITLE
Health probe configuration should be applied to specific port.

### ISSUE THREAD

**Issue by MartinForReal** [kubernetes-sigs/cloud-provider-azure#949]
#### What happened:

Health probe configurations are applied to all ports of the service. 

#### What you expected to happen:

Health probe configuration should be applied to specific port.

#### How to reproduce it (as minimally and precisely as possible):

```yaml
apiVersion: v1
kind: Service
metadata:
  name: sctpservice
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-health-probe-protocol: "tcp"
spec:
  type: LoadBalancer
  selector:
    app: sctpserver
  ports:
    - name: sctpserver
      protocol: SCTP
      port: 30102
      targetPort: 30102
    - name: webserver
      protocol: TCP
      port: 80
      targetPort: 30102
```

#### Anything else we need to know?:

Nothing else

#### Environment:
 Not needed.
